### ISSUE TITLE
Reset via DTR pin is broken

### ISSUE THREAD

**Issue by roybaer** [gicking/stm8gal#10]
Resetting a board via DTR pin does not work anymore.
The guilty commit appears to be cd470a76115f46474f921ac9d04b7dfde54588b6, which kind of makes sense. I.e. you'll have to open the port before you can toggle DTR.

**Comment by gicking** [comment]
hi roybaer,

thanks for pointing that out! You are correct, port must be opened before DTR reset. In old versions the port was indeed opened before reset, but I changed the sequence because I had issues with USB port not flushing correctly (see also [here](https://stackoverflow.com/questions/13013387/clearing-the-serial-ports-buffer)).  

To fix the bug without the flush issue, I just uploaded a fix to branch `develop` (not yet `master`). This opens the port, resets via DTR and closes the port again, see [here](https://github.com/gicking/stm8gal/blob/b476ba9edfeabf4f02c1af52e695ad556e134b86/main.c#L505).

Can you please check it and let me know if this fixes your problem? Thanks in advance!

**Comment by roybaer** [comment]
I can confirm that this solves the DTR reset problem.
However, I cannot get anything past 1d91c125705a6a1a41ec84a33b4a8f2c39ae2de8 to work. That problem appears to be unrelated, though.
Can you cherry-pick this fix into the master branch?

**Comment by gicking** [comment]
Darn! 

1) just added the fix to the `master` branch, like requested.

2) I implemented many improvements and bugfixes (at least with my setup) in the `develop` branch. I would hate to go back to `master` again! 
Could you please be more specific what exactly doesn't work, which OS you're using, and which board / STM8 variant is not working...? Maybe it's due to a different behavior of the ROM bootloader, which I couldn't test...? Thanks in advance!

**Comment by roybaer** [comment]
Thanks! `master` works well, now.
I've opened #11 for the unrelated issue, so this can be closed.
